### ISSUE TITLE
Organisation of the whole project

### ISSUE THREAD

**Issue by chaolmu** [chaolmu/flypulator_simulation#2]
I would like to  change the organisation of the git repository as following:
Level0 flypulator
Level1 flypulator_simulation, flypulator_tracking_ctrl, flypulator_traj_gen, flypulator_description, flypulator_msg, flypulator_teleopration
Level2 {flypulator_plugin_aero, flypulator_plugin_control, flypulator_simulation_gazebo etc.}, {flypulator_ism, flypulator_backstepping, flypulator_pid, etc.}

What do you guys think? Anyone knows how to collect several git repositories to one meta?

**Comment by danneboom** [comment]
So the following folder structure? Feel free to edit.. and please assign issues to me, so i get a message

flypulator/
     flypulator_description/
     flypulator_simulation/
           flypulator_plugin_aero
           flypulator_simulation_gazebo
           [more?]
     flypulator_control/      // better readable than flypulator_tracking_ctrl
           flypulator_ism/
           [other control strategies]
     flypulator_traj_generator/

And a single git repository?

**Comment by chaolmu** [comment]
@danneboom Yes, the folder structure should be like this. What I want to disscuss is, if we use a single git repository or separated repositories for each ros package in leve 1?

**Comment by danneboom** [comment]
Sounds a little complicated and not so easy to use... since the project is not too large I would prefer one main git repository.

**Comment by JinyaoZhu** [comment]
Yes, it seems a bit over-modularized.

**Comment by danneboom** [comment]
maybe we should use a single catkin workspace for flypulator (e.g. flypulator_ws), so we can omit one level and metapackage confusion. The workspace can then be the repository path, and devel/ and build/ can be ignored via .gitignore

**Comment by chaolmu** [comment]
Good idea. I have actually already a separated workspace for flypulator. I will reorganize the repositories tonight.

**Comment by danneboom** [comment]
Little update to file structure concerning different controllers: The implementation will allow changing the controllers via parameter, so there is no need for different packages. Most code is for message receive and send and parameter call, so it can be reused. So the structure should be


* flypulator/
     * flypulator_description/
     * flypulator_simulation/
           * flypulator_plugin_aero
           * flypulator_simulation_gazebo
           * [more?]
     * flypulator_controll/      // better readable than flypulator_tracking_ctrl
           * src/
                  * sliding_mode_controller.cpp
                  * [any other controller].cpp
                  * base_controller.cpp
                  * controller_node.cpp // or similar file name
     * flypulator_traj_generator/

**Comment by chaolmu** [comment]
Hi guys,
I have merged all repositories based on decided folder structure.
catkin_make is successful for all other packages except flypulator_control, since there is no src.
Please change to the new repository at FLYing-maniPULATOR immediately. Old repositories should be deleted after validation of the new repository.
good night!

**Comment by chaolmu** [comment]
new issuses pls create in new repo.
